global abstract with sharing class AbstractController {
    public AbstractController() {

    }
    
    // global class APIWrapper {
    //     global List<Object> results;
    //     global String errorMessage;
    //     global Integer code;

    //     global AbstractController.APIWrapper withResult(List<Object> results) {
    //         this.results = results;
    //         return this;
    //     }

    //     global AbstractController.APIWrapper withCode(Integer code) {
    //         this.code = code;
    //         return this;
    //     }


    //     global AbstractController.APIWrapper withErrorMessage(String errorMessage) {
    //         this.errorMessage = errorMessage;
    //         return this;
    //     }
    // }
}